### ISSUE TITLE
Add ability to change order of sheets shown

### ISSUE THREAD

**Issue by mcgovey** [mcgovey/Qlik-Sense-MyTabs-Extension#7]
As suggested on Qlik Branch, add the ability to change the order that the sheets are displayed.

**Comment by andrew134598** [comment]
Hello, what is a status of the issue?
The ability to change order of sheets is very important. Please let my know if you are going to fix it?

Regards,
 Jacek

**Comment by mcgovey** [comment]
Hi @andrew134598,
I'm no longer actively maintaining this project. If you want to make changes feel free to do so. Please send a pull request with the updated package and I'll happily merge it back in so others can use.
Thanks!
Kevin
